package com.ketee_jishs.nasa_app.util

const val CHIPS_SHARED_PREFS_NAME = "CHIPS_SHARED_PREFS_NAME"
const val KEY_CHIP = "TODAY_CHIP_KEY"
const val CHECKED_TODAY = 1
const val CHECKED_YESTERDAY = 2
const val CHECKED_DAY_BEFORE_YESTERDAY = 3

const val THEME_PREFS_NAME = "THEME_PREFS_NAME"
const val KEY_THEME = "KEY_THEME"
const val THEME_DAY = 0
const val THEME_NIGHT = 1

const val SCREEN_PREFS_NAME = "SCREEN_PREFS_NAME"
const val KEY_SCREEN = "KEY_SCREEN"
const val PICTURE_SCREEN = 0
const val SETTINGS_SCREEN = 1

const val TODAY_EARTH_FRAGMENT = 0
const val YESTERDAY_EARTH_FRAGMENT = 1
const val DAY_BEFORE_YESTERDAY_EARTH_FRAGMENT = 2

const val TODAY_MARS_FRAGMENT = 0
const val YESTERDAY_MARS_FRAGMENT = 1
const val DAY_BEFORE_YESTERDAY_MARS_FRAGMENT = 2